version: '2'
services:
    hao-app:
        image: hao
        external_links:
            - hao-mysql:mysql
            - hao-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/hao?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    hao-mysql:
        extends:
            file: mysql.yml
            service: hao-mysql
    hao-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: hao-elasticsearch
